name: Gradle 8.9 Clean Setup and Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Remove old Gradle wrapper files
        run: |
          rm -f gradlew gradlew.bat
          rm -rf gradle/wrapper

      - name: Install Gradle CLI
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.9

      - name: Generate new wrapper with Gradle 8.9
        run: gradle wrapper --gradle-version 8.9

      - name: Commit and push new wrapper files
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add gradlew gradlew.bat gradle/wrapper
          git diff --cached --quiet || git commit -m "Update Gradle wrapper to 8.9"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run clean and build
        run: ./gradlew clean build --warning-mode all --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
