name: Update Gradle Wrapper and Build Debug APK

on:
  push:
    branches:
      - main

jobs:
  update-wrapper-and-build:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout repository (with GH_TOKEN)
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-cache-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-cache-${{ runner.os }}-

      - name: Remove existing Gradle wrapper files
        run: |
          echo "Eski gradle wrapper dosyaları siliniyor..."
          rm -rf gradlew gradlew.bat gradle/wrapper/

      - name: Generate Gradle wrapper 8.5.1
        run: |
          echo "Gradle wrapper 8.5.1 sürümü oluşturuluyor..."
          ./gradlew wrapper --gradle-version 8.5.1
        # Eğer gradle yoksa hata verir, alternatif olarak localde oluşturup pushlayabilirsin

      - name: Commit and push updated gradle wrapper files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add gradlew gradlew.bat gradle/wrapper/
          git diff --quiet && echo "Değişiklik yok, commit atılmayacak." || (git commit -m "Update gradle wrapper to 8.5.1" && git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }})

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload Debug APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
