name: Build Android Debug APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-cache-${{ hashFiles('**/*.gradle', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-cache-

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Download and Install Gradle 8.14.3
        run: |
          wget https://services.gradle.org/distributions/gradle-8.14.3-bin.zip
          unzip -q gradle-8.14.3-bin.zip
          echo "GRADLE_HOME=$PWD/gradle-8.14.3" >> $GITHUB_ENV
          echo "$PWD/gradle-8.14.3/bin" >> $GITHUB_PATH

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew || true

      - name: Clean Project
        run: ./gradlew clean

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload Debug APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
